version: 0.2

env:
  variables:
    S3_BUCKET: "springboot-lambda-deep"
    ARTIFACT_NAME: "employee-app.zip"
    REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
      - mvn -version

  build:
    commands:
      - echo Building project with Maven...
      - mvn clean package -DskipTests
      - echo Zipping compiled project...
      - zip -r $ARTIFACT_NAME target/*

  post_build:
    commands:
      - echo Uploading ZIP to S3...
      - aws s3 cp $ARTIFACT_NAME s3://$S3_BUCKET/$ARTIFACT_NAME
      - echo Build and upload completed successfully.

artifacts:
  files:
    - $ARTIFACT_NAME

cache:
  paths:
    - "/root/.m2/**/*"
